 ldap:
    container_name: contosoOpenLdap
    image: osixia/openldap:latest
    ports: 
      - "389:389"
      - "636:636"
    env_file:
      - ./docker-openLdap.env
    volumes:
      - ./:/data/ldif
